### ISSUE TITLE
输出最大结果不对

### ISSUE THREAD

**Issue by ningluninglu** [nanamare/ncnn_mobilenet#1]
最大的score一直
04-27 15:11:58.899  8832  9135 D top_class max_score: 502 0.001069
04-27 15:11:59.165  8832  9135 D top_class max_score: 0 0.001024
04-27 15:11:59.165  8832  9135 D top_class max_score: 5 0.001043
04-27 15:11:59.165  8832  9135 D top_class max_score: 24 0.001056
04-27 15:11:59.165  8832  9135 D top_class max_score: 29 0.001062
04-27 15:11:59.166  8832  9135 D top_class max_score: 75 0.001068
04-27 15:11:59.166  8832  9135 D top_class max_score: 561 0.001074
04-27 15:11:59.421  8832  9135 D top_class max_score: 0 0.001023
04-27 15:11:59.421  8832  9135 D top_class max_score: 5 0.001035
请问是什么情况

**Comment by Nanamare** [comment]
@ningluninglu 
top_class max_score: 502(label Index) 0.001069 (probability)

You just choose high probability & Index
MobilnetV1 consists of 1000 classification. (0 ~ 999 Index)

Example log
```
05-07 19:46:47.669 12431-12451/com.nanamare.mac.mobilenet D/Output probability: 47 :  0.001005
    48 :  0.001013
    49 :  0.001009
    50 :  0.001008
    51 :  0.000994
    52 :  0.001005
    53 :  0.001003
    54 :  0.001009
    55 :  0.001021
    56 :  0.000998
    57 :  0.000993
    58 :  0.000998
    59 :  0.000993
    60 :  0.001008
    61 :  0.001003
    62 :  0.001002
    63 :  0.000993
    64 :  0.001012
    65 :  0.000997
    66 :  0.001007
    67 :  0.001008
    68 :  0.000994
    69 :  0.000994
    70 :  0.000993
    71 :  0.001002
    72 :  0.001011
    73 :  0.000993
    74 :  0.001005
    75 :  0.001016
    76 :  0.000995
    77 :  0.000997
    78 :  0.001032
    79 :  0.001007
    80 :  0.001004
    81 :  0.001002
    82 :  0.000993
    83 :  0.001012
    84 :  0.001006
    85 :  0.001035
    86 :  0.000997
    87 :  0.001006
    88 :  0.000997
    89 :  0.001022
    90 :  0.000997
    91 :  0.001005
    92 :  0.001038
    93 :  0.000995
    94 :  0.001010
    95 :  0.001009
    96 :  0.001023
    97 :  0.000993
    98 :  0.000993
    99 :  0.000994
    100 :  0.001006
05-07 19:46:47.675 12431-12451/com.nanamare.mac.mobilenet D/NCNN Inference time cost:: 122
05-07 19:46:47.675 12431-12451/com.nanamare.mac.mobilenet D/NCNN  Label ::  ground beetle, carabid beetle' = 0.001
```
